// Build step 1: read the site's content out of dmart, through its PUBLIC API.
//
// This is the part of the repository the demo is about. Everything the site
// shows — pages, navigation, the landing page — lives in a dmart space (the
// `website` pack in ../pack), and this script fetches it exactly as any
// anonymous visitor could: `POST {DMART_URL}/public/query` via the official
// TypeScript SDK. What the `world`-facing permissions don't expose, the site
// can't publish.
//
// It writes:
//   src/content/site.json        brand, header links, docs nav, footer, base URL
//   src/content/home.json        the landing page, markdown already rendered
//   src/content/pages/<slug>.json one per page, markdown already rendered
//   src/routes/<slug>/index.svelte a static route per page, so the build
//                                 prerenders every one to real HTML
//
// Environment:
//   DMART_URL   dmart API base (default https://dmart.cc/dmart — the live site)
//   DMART_SPACE the space to read (default website)

import axios from "axios";
import { Dmart, DmartScope, QueryType, ResourceType } from "@edraj/tsdmart";
import { mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync, existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { renderMarkdown, renderMarkdownNoLinks, renderInline, hasLeadingHeading, plainText } from "./markdown.mjs";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const CONTENT = join(ROOT, "src/content");
const ROUTES = join(ROOT, "src/routes");
const GENERATED = "<!-- generated by scripts/export-content.mjs — do not edit -->";

const url = (process.env.DMART_URL || "https://dmart.cc/dmart").replace(/\/+$/, "");
const space = process.env.DMART_SPACE || "website";

Dmart.setAxiosInstance(axios.create({ baseURL: url, timeout: 30000 }));

async function query(subpath) {
    const res = await Dmart.query(
        {
            type: QueryType.subpath,
            space_name: space,
            subpath,
            exact_subpath: true,
            filter_types: [ResourceType.content],
            retrieve_json_payload: true,
            search: "",
            limit: 1000,
        },
        DmartScope.public,
    );
    if (res?.status !== "success") throw new Error(`public/query ${space}${subpath}: ${JSON.stringify(res?.error ?? res)}`);
    return res.records ?? [];
}

const lang = (d) => (d && typeof d === "object" ? d.en ?? Object.values(d)[0] ?? "" : "");

const [pageRecords, siteRecords] = await Promise.all([query("/pages"), query("/site")]);
if (pageRecords.length === 0 && siteRecords.length === 0) {
    console.error(`export: ${url} returned nothing an anonymous visitor can read in '${space}' — is the pack installed and public (pack/install.sh --public)?`);
    process.exit(2);
}

// ── site config ──────────────────────────────────────────────────────────────
const configBody = siteRecords.find((r) => r.shortname === "config")?.attributes?.payload?.body ?? {};
const site = {
    brand: configBody.brand ?? "Site",
    titleSuffix: configBody.title_suffix ?? "",
    baseUrl: (process.env.SITE_URL || configBody.base_url || "").replace(/\/+$/, ""),
    headerLinks: (configBody.header_links ?? []).map((l) => ({ label: l.label, href: l.href, docs: !!l.docs })),
    nav: (configBody.nav ?? []).map((g) => ({ title: g.title ?? "", items: g.items ?? [] })),
    footerHtml: renderMarkdown(configBody.footer ?? ""),
    source: url,
};

// ── pages ────────────────────────────────────────────────────────────────────
const pages = pageRecords
    .map((r) => {
        const a = r.attributes ?? {};
        const slug = (a.slug && a.slug.trim()) || r.shortname;
        const type = a.payload?.content_type ?? "markdown";
        const body = typeof a.payload?.body === "string" ? a.payload.body : "";
        const html = type === "markdown" ? renderMarkdown(body) : type === "html" ? body : `<pre>${escapeHtml(body)}</pre>`;
        return {
            slug,
            shortname: r.shortname,
            title: lang(a.displayname) || r.shortname,
            description: plainText(lang(a.description)),
            updatedAt: a.updated_at ?? null,
            leadingHeading: hasLeadingHeading(body, type),
            hasDiagram: html.includes('<pre class="mermaid">'),
            html,
        };
    })
    .filter((p) => /^[a-z0-9][a-z0-9-]*$/.test(p.slug));

const bySlug = new Map(pages.map((p) => [p.slug, p]));
const docSlugs = new Set(site.nav.flatMap((g) => g.items.map((i) => i.page)).filter((s) => bySlug.has(s)));
site.nav = site.nav
    .map((g) => ({ title: g.title, items: g.items.filter((i) => bySlug.has(i.page)).map((i) => ({ slug: i.page, label: i.label || bySlug.get(i.page).title })) }))
    .filter((g) => g.items.length > 0);

// ── landing page ─────────────────────────────────────────────────────────────
const homeRecord = siteRecords.find((r) => r.shortname === "home");
const h = homeRecord?.attributes?.payload?.body ?? {};
const actions = (list) => (list ?? []).filter((x) => x.label && x.href).map((x) => ({ label: x.label, href: x.href, style: ["primary", "secondary", "link"].includes(x.style) ? x.style : "primary" }));
const home = homeRecord && {
    title: lang(homeRecord.attributes.displayname) || site.brand,
    description: plainText(lang(homeRecord.attributes.description)),
    updatedAt: homeRecord.attributes.updated_at ?? null,
    badge: h.hero?.badge ?? "",
    titleLines: (h.hero?.title_lines ?? []).filter(Boolean),
    subtitleHtml: renderInline(h.hero?.subtitle ?? ""),
    actions: actions(h.hero?.actions),
    figure: h.hero?.figure ?? null,
    stats: (h.stats ?? []).map((s) => ({ value: s.value ?? "", label: s.label ?? "" })),
    sections: (h.sections ?? []).map((s) => ({
        id: /^[a-z0-9-]+$/.test(s.id ?? "") ? s.id : null,
        kind: ["cards", "steps", "figures", "explainer", "prose", "banner"].includes(s.kind) ? s.kind : "prose",
        title: s.title ?? "",
        accent: s.accent ?? "",
        bodyHtml: renderMarkdown(s.body ?? ""),
        figure: s.figure ?? null,
        items: (s.items ?? []).map((i) => ({
            title: i.title ?? "",
            // A card with an href is a link itself, so its body can't hold one.
            bodyHtml: s.kind === "figures" ? renderInline(i.body ?? "") : i.href ? renderMarkdownNoLinks(i.body ?? "") : renderMarkdown(i.body ?? ""),
            href: i.href ?? null,
            icon: i.icon ?? null,
        })),
        actions: actions(s.actions),
    })),
};

// ── write ────────────────────────────────────────────────────────────────────
rmSync(CONTENT, { recursive: true, force: true });
mkdirSync(join(CONTENT, "pages"), { recursive: true });
writeFileSync(join(CONTENT, "site.json"), JSON.stringify(site, null, 2));
writeFileSync(join(CONTENT, "home.json"), JSON.stringify(home ?? null, null, 2));
writeFileSync(
    join(CONTENT, "index.json"),
    JSON.stringify(pages.map((p) => ({ slug: p.slug, title: p.title, updatedAt: p.updatedAt, doc: docSlugs.has(p.slug) })), null, 2),
);
for (const p of pages) writeFileSync(join(CONTENT, "pages", `${p.slug}.json`), JSON.stringify({ ...p, doc: docSlugs.has(p.slug) }, null, 2));

// One static route per page. Generated folders carry a marker so a later
// export removes exactly the ones it made, never a hand-written route.
for (const entry of readdirSync(ROUTES, { withFileTypes: true })) {
    const file = join(ROUTES, entry.name, "index.svelte");
    if (entry.isDirectory() && existsSync(file) && readFileSync(file, "utf8").startsWith(GENERATED))
        rmSync(join(ROUTES, entry.name), { recursive: true });
}
for (const p of pages) {
    if (existsSync(join(ROUTES, p.slug))) throw new Error(`a hand-written route already owns /${p.slug}`);
    mkdirSync(join(ROUTES, p.slug));
    writeFileSync(
        join(ROUTES, p.slug, "index.svelte"),
        `${GENERATED}\n<script>\n  import Page from "$lib/Page.svelte";\n  import page from "$content/pages/${p.slug}.json";\n</script>\n\n<Page {page} />\n`,
    );
}

console.log(`export: ${pages.length} page(s)${home ? " + home" : ""} from ${url}/public/query (space '${space}')`);

function escapeHtml(s) {
    return s.replace(/[&<>"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[c]);
}
